services:
  - type: web
    name: stockwave-ims
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
